db:
  username: ${username.value:postgres}
  password: postgres1
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
spring.profiles.active: qa
spring:
  mvc:
#    format:
#      date: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          batch_size: 50
          fetch_size: 50
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 444618376803-t25mkqkbv7mcjacagj444eaua3hrgb7q.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile


logging:
  level:
    root: INFO
    com.minorm.spring.database.pool.ConnectionPool: INFO
    org.springframework.jdbc.core: TRACE


springdoc:
  swagger-ui:
    oauth:
      client-id: 444618376803-t25mkqkbv7mcjacagj444eaua3hrgb7q.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
